export const UsersSeed = [
  {
    firstName: 'Admin',
    lastName: 'Greelow',
    email: 'admin@admin.com',
    password: '$2b$10$Bh6zRx.nIoaYwQWCkMJbPu4R9FDs0cDB1c7J/K.ikgDEVX5FTFTsG',
    phone: '4343-4343',
    isAdmin: true,
    address: 'Angel Gallardo 551',
    deviceToken: null,
    dateOfBirth: new Date('2000-01-01'),
    lastPurchase: new Date(),
  },
  {
    firstName: 'Active',
    lastName: 'User',
    email: 'active@user.com',
    password: '$2b$10$Bh6zRx.nIoaYwQWCkMJbPu4R9FDs0cDB1c7J/K.ikgDEVX5FTFTsG',
    phone: '4343-4343',
    isAdmin: false,
    address: 'Angel Gallardo 15151',
    deviceToken: null,
    dateOfBirth: new Date('1998-10-02'),
    lastPurchase: null,
  },
  {
    firstName: 'Inactive',
    lastName: 'User',
    email: 'inactive@user.com',
    password: '$2b$10$Bh6zRx.nIoaYwQWCkMJbPu4R9FDs0cDB1c7J/K.ikgDEVX5FTFTsG',
    phone: '4343-4343',
    isAdmin: false,
    address: 'Angel Gallardo 15151',
    deviceToken: null,
    dateOfBirth: new Date('1994-05-10'),
    lastPurchase: null,
  },
];
